title: STEM Blog
description: A professional blog about science, technology, engineering, and math
theme: minima
plugins:
  - jekyll-feed
markdown: kramdown
url: "https://meteorinca.github.io"
baseurl: "/STEMblog"
